#!/bin/bash
#wget https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts && echo "file ./hosts got updated from the internet!" || echo "failed"
curl -o hosts https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts && echo "success!" || echo "failed"
